//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class form_master
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public Nullable<int> mobile { get; set; }
        public string country { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string enter_by { get; set; }
    }
}
